SELECT r.FOOD_TYPE, r.REST_ID, r.REST_NAME, r.FAVORITES
FROM REST_INFO r LEFT JOIN 
(SELECT FOOD_TYPE, MAX(FAVORITES) as C
FROM REST_INFO
GROUP BY FOOD_TYPE) as t ON r.FAVORITES = t.C AND r.FOOD_TYPE = t.FOOD_TYPE
WHERE C IS NOT NULL 
ORDER BY FOOD_TYPE DESC