SELECT ANIMAL_ID, NAME
FROM
(SELECT i.ANIMAL_ID, i.NAME, DATEDIFF(o.DATETIME, i.DATETIME) as PERIOD
FROM ANIMAL_INS i JOIN ANIMAL_OUTS o on i.ANIMAL_ID = o.ANIMAL_ID) as t
ORDER BY PERIOD DESC LIMIT 2

