SELECT DATE_FORMAT(o.SALES_DATE, '%Y') AS YEAR, MONTH(o.SALES_DATE) AS MONTH, COUNT(DISTINCT o.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT o.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = '2021') , 1) AS PURCHASED_RATIO
FROM ONLINE_SALE o INNER JOIN USER_INFO u ON u.USER_ID = o.USER_ID 
WHERE DATE_FORMAT(u.JOINED, '%Y') = '2021'
GROUP BY DATE_FORMAT(o.SALES_DATE, '%m') 
ORDER BY YEAR asc, MONTH asc