SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
FROM ANIMAL_INS i JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE SEX_UPON_INTAKE LIKE "%Intact%" and (SEX_UPON_OUTCOME LIKE "%Neutered%" or SEX_UPON_OUTCOME LIKE "%Spayed%")
ORDER BY ANIMAL_ID