WITH RECURSIVE CTE AS (
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM + 1 FROM CTE
    WHERE NUM < 23
)

SELECT c.NUM as HOUR, IF(COUNT(ANIMAL_ID) IS NULL, 0, COUNT(ANIMAL_ID)) as COUNT 
FROM (SELECT HOUR(DATETIME) AS HOUR, ANIMAL_ID FROM ANIMAL_OUTS) as a right join CTE c
on c.NUM = a.HOUR
GROUP BY c.NUM
ORDER BY c.NUM