SELECT u.USER_ID, NICKNAME, CONCAT(CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2) as 전체주소, CONCAT(SUBSTRING(TLNO, 1, 3), "-", SUBSTRING(TLNO, 4, 4), "-", SUBSTRING(TLNO, 8, 4)) as 전화번호
FROM USED_GOODS_BOARD b LEFT JOIN USED_GOODS_USER u ON b.WRITER_ID = u.USER_ID
GROUP BY WRITER_ID
HAVING COUNT(BOARD_ID) > 2
ORDER BY USER_ID desc