SELECT FLAVOR FROM (SELECT f.FLAVOR, f.TOTAL_ORDER + j.TOTAL_ORDER AS TOTAL_ORDER 
FROM FIRST_HALF f right join 
(SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM JULY GROUP BY FLAVOR) AS j
on f.FLAVOR = j.FLAVOR
ORDER BY TOTAL_ORDER DESC LIMIT 3) as p