-- 코드를 입력하세요
SELECT CATEGORY, MAX(PRICE) as MAX_PRICE, (SELECT PRODUCT_NAME FROM FOOD_PRODUCT WHERE CATEGORY = p.CATEGORY ORDER BY PRICE DESC LIMIT 1) AS PRODUCT_NAME
FROM FOOD_PRODUCT p
WHERE CATEGORY = "과자" or category = "국" or category = "김치" or category = "식용유"
GROUP BY CATEGORY
order by MAX_PRICE desc