SELECT s.ROUTE, CONCAT(ROUND(SUM(s.D_BETWEEN_DIST), 1), 'km') as TOTAL_DISTANCE, CONCAT(ROUND(SUM(s.D_BETWEEN_DIST) / COUNT(DISTINCT(s.NO)), 2), 'km') as AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE s
GROUP BY s.ROUTE
ORDER BY SUM(s.D_BETWEEN_DIST) DESC