-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, SUM(o.SALES_AMOUNT) * p.PRICE AS SALES
FROM PRODUCT p JOIN OFFLINE_SALE o on o.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SALES DESC, p.PRODUCT_CODE