-- 코드를 입력하세요
SELECT 
    TITLE, 
    USED_GOODS_BOARD.BOARD_ID, 
    REPLY_ID, 
    USED_GOODS_REPLY.WRITER_ID, 
    USED_GOODS_REPLY.CONTENTS, 
    DATE_FORMAT(USED_GOODS_REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE 
FROM 
    USED_GOODS_BOARD, USED_GOODS_REPLY
WHERE USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID AND DATE_FORMAT(USED_GOODS_BOARD.CREATED_DATE, '%Y-%m-%d') < DATE_FORMAT('2022-11-01', '%Y-%m-%d')
ORDER BY CREATED_DATE, TITLE