-- 코드를 입력하세요
SELECT HISTORY_ID, ROUND(RENT_DURATION * DAILY_FEE * (100 - DISCOUNT_RATE) / 100, 0) AS FEE
FROM (SELECT HISTORY_ID, CAR_ID, t.CAR_TYPE, RENT_DURATION, DAILY_FEE, DURATION_TYPE + 0, MAX(IF(DURATION_TYPE + 0 <= RENT_DURATION, DISCOUNT_RATE, 0)) AS DISCOUNT_RATE 
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN p join
(SELECT HISTORY_ID, h.CAR_ID, TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 AS RENT_DURATION, CAR_TYPE, DAILY_FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h JOIN CAR_RENTAL_COMPANY_CAR c on h.CAR_ID = c.CAR_ID) AS t
on t.CAR_TYPE = p.CAR_TYPE
GROUP BY HISTORY_ID) AS K
WHERE CAR_TYPE = "트럭"
ORDER BY FEE DESC, HISTORY_ID DESC
